title: Surplex Docs
description: Documentation for your Surplex VR Tracking Shoes
# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

url: https://surplex-io.github.io
# color_scheme: dark


# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
