title: Surplex Docs
description: Documentation for your Surplex VR Tracking Shoes
# theme: just-the-docs
remote_theme: just-the-docs/just-the-docs

url: https://surplex-io.github.io

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
